{% set name = "napari-nibabel" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-nibabel-{{ version }}.tar.gz
  sha256: 86578850f923ce2c192391a0565a60169010b2aa1461584bbce777dd2a13bb8c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - nibabel
    - numpy
    - pydicom
    - python >=3.8

test:
  imports:
    - napari_nibabel
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/napari-nibabel/
  summary: Read access to some common neuroimaging file formats
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
